### ISSUE TITLE
Shane isn't top of the leaderboard

### ISSUE THREAD

**Issue by shanetuohy** [rob7117/Foosbot#4]
Something is clearly wrong with the bot. It's saying that Shane isn't top of all of the leaderboards.

**Comment by Pwezem** [comment]
Can't seem to replicate this issue. Please reboot and try scoring more goals.

**Comment by rob7117** [comment]
@shanetuohy Assigning you to fix this. Not sure if you'll ever get it done.

**Comment by shanetuohy** [comment]
Took it upon myself to fix this one. 

Shane is currently top of conceded/game, goals/game and win percentage. 

Closing this issue. 

![image](https://user-images.githubusercontent.com/3654645/28167181-9fd3abc2-67d2-11e7-8339-69cfcc48d3f8.png)
